document.write("<"+"script type=\"text/javascript\" src=\"http://cdn.hadj7.adjuggler.net/banners/rtb/rtb_8.0.5_3.js\"><"+"/script>\n");
document.write("<"+"script type=\"text/javascript\">\n");
document.write("(function () {\n");
document.write("function show_ad(rtb) {\n");
document.write("var request = {\n");
document.write("'aj_ecpm' : 0\n");
document.write("};\n");
document.write("rtb.script_url = 'http://cdn.hadj7.adjuggler.net/banners/';\n");
document.write("rtb.confirm_banner_url = 'http://mshakers.rotator.hadj7.adjuggler.net/servlet/ajrotator/327635/0/impr?ajkey=V12467600B6J-573J8020L220995129452DC7L327639L327638QL221013QQP0G01H16247BX13CLICK_URL_ENC7DG0Q0B851BF200000101000046';\n");
document.write("rtb.ad_height = '600';\n");
document.write("rtb.above_the_fold_threshold = 0.5;\n");
document.write("rtb.pubmatic.server_url = 'http://bid.pubmatic.com/AdServer/AdServerServlet';\n");
document.write("request['pubmatic_request'] = {\n");
document.write("'price_floor' : 0.14,\n");
document.write("'pubId' : 29297,\n");
document.write("'siteId' : 31882,\n");
document.write("'adId' : 31407,\n");
document.write("'kadwidth' : 160,\n");
document.write("'kadheight' : 600,\n");
document.write("'kltstamp' : '2014-02-24+20%3A13%3A38',\n");
document.write("'price_floor_offset' : 0,\n");
document.write("'pageURL' : '%24%7BREFERER_URL%7D',\n");
document.write("'kadpageurl': '%24%7BREFERER_URL%7D',\n");
document.write("'ranreq' : 0.6979609813282373\n");
document.write("};\n");
document.write("rtb.openrtb.server_url = 'http://yorick.adjuggler.net/openrtb/1.0/json';\n");
document.write("request['openrtb_request'] = {\n");
document.write("'zone' : 220995,\n");
document.write("'pub' : 327634,\n");
document.write("'adspot' : 327635,\n");
document.write("'cluster' : 'hadj7',\n");
document.write("'country' : 'eg',\n");
document.write("'price_floor_offset' : 0,\n");
document.write("'rnd' : 0.576038538584625,\n");
document.write("'price_floor' : 0,\n");
document.write("'url' : '%24%7BREFERER_URL%7D',\n");
document.write("'width' : 160,\n");
document.write("'height' : 600\n");
document.write("};\n");
document.write("function show_aj_ad() {\n");
document.write("document.write(\"<"+"\"+\"a href=\\\"https://www.facebook.com/pages/Fans-of-Robbie-Gil/241251159901\\\" target=\\\"_blank\\\"><"+"\"+\"img src=\\\"http://srv4.mediashakers.com/robbiegil/Robbie-Gil-LIKE-160x600.jpg\\\" width=\\\"160\\\" height=\\\"600\\\" border=\\\"0\\\"><"+"\"+\"/a>\");\n");
document.write("\n");
document.write("}\n");
document.write("rtb.callAllSources(request, show_aj_ad);\n");
document.write("}\n");
document.write("/* Since IE doesn't guarantee JS execution order, we need to store this ad until rtb.js was successfully loaded */\n");
document.write("if (window.adjuggler && window.adjuggler.rtb) {\n");
document.write("show_ad(window.adjuggler.rtb);\n");
document.write("} else {\n");
document.write("if (!window.adjuggler) {\n");
document.write("window.adjuggler = {\n");
document.write("waiting_ads : []\n");
document.write("};\n");
document.write("}\n");
document.write("window.adjuggler.waiting_ads.push(show_ad);\n");
document.write("}\n");
document.write("})();\n");
document.write("<"+"/script>");
