document.write("<"+"script type=\"text/javascript\" src=\"http://cdn.hadj7.adjuggler.net/banners/rtb/rtb_8.0.5_3.js\"><"+"/script>\n");
document.write("<"+"script type=\"text/javascript\">\n");
document.write("(function () {\n");
document.write("function show_ad(rtb) {\n");
document.write("var request = {\n");
document.write("'aj_ecpm' : 0\n");
document.write("};\n");
document.write("rtb.script_url = 'http://cdn.hadj7.adjuggler.net/banners/';\n");
document.write("rtb.confirm_banner_url = 'http://mshakers.rotator.hadj7.adjuggler.net/servlet/ajrotator/342879/0/impr?ajkey=V1280270DD9J-573J8020L220995129452DC7L343088L343085QL221012QQP0G01I295W4http3A2F2FW4ams12E69622EW5adnxs2EW3com2FW5click3FX14CRueXinLcD9Eyk2DX14qfTpuPw4tsp3vp2DY141o_RMpPqn06bj8JG55eKctwP1uwBar1HbBaayrOzxnuvl26pwtTAAAAAOqXIgBEAQAAMgMAAAIAAACaFbUA6JMFAAAAAQBVU0QAVVNEANgCWgBSigAAQbkAAgUCAQIAAIwADSUgpwAAAAA2E2FW3cnd3D21X27fAYgPgjg2a4BEJqr1AUY6KcWIAA2E2FW8referrer3DW4http3A2F2FW3www2EW4spoj2EW3com2FW8problems2FW8MKLABELS2F2FW8clickenc3DG0Q0B851BBF00000101000012';\n");
document.write("rtb.ad_height = '90';\n");
document.write("rtb.above_the_fold_threshold = 0.5;\n");
document.write("rtb.pubmatic.server_url = 'http://bid.pubmatic.com/AdServer/AdServerServlet';\n");
document.write("request['pubmatic_request'] = {\n");
document.write("'price_floor' : 0.14,\n");
document.write("'pubId' : 29297,\n");
document.write("'siteId' : 31882,\n");
document.write("'adId' : 31405,\n");
document.write("'kadwidth' : 728,\n");
document.write("'kadheight' : 90,\n");
document.write("'kltstamp' : '2014-02-24+20%3A12%3A47',\n");
document.write("'price_floor_offset' : 0,\n");
document.write("'pageURL' : 'http%3A%2F%2Fwww.spoj.com',\n");
document.write("'kadpageurl': 'http%3A%2F%2Fwww.spoj.com',\n");
document.write("'ranreq' : 0.010992212453673433\n");
document.write("};\n");
document.write("rtb.openrtb.server_url = 'http://yorick.adjuggler.net/openrtb/1.0/json';\n");
document.write("request['openrtb_request'] = {\n");
document.write("'zone' : 220995,\n");
document.write("'pub' : 342878,\n");
document.write("'adspot' : 342879,\n");
document.write("'cluster' : 'hadj7',\n");
document.write("'country' : 'eg',\n");
document.write("'price_floor_offset' : 0,\n");
document.write("'rnd' : 0.8681145636102165,\n");
document.write("'price_floor' : 0,\n");
document.write("'url' : 'http%3A%2F%2Fwww.spoj.com%2Fproblems%2FMKLABELS%2F',\n");
document.write("'width' : 728,\n");
document.write("'height' : 90\n");
document.write("};\n");
document.write("function show_aj_ad() {\n");
document.write("document.write(\"<"+"\"+\"script type=\\\"text/javascript\\\" src=\\\"http://ap.lijit.com///www/delivery/fpi.js?z=237259&u=mediashakers&width=728&height=90&loc={REFERER_URL}\\\"><"+"\"+\"/script>\");\n");
document.write("\n");
document.write("}\n");
document.write("rtb.callAllSources(request, show_aj_ad);\n");
document.write("}\n");
document.write("/* Since IE doesn't guarantee JS execution order, we need to store this ad until rtb.js was successfully loaded */\n");
document.write("if (window.adjuggler && window.adjuggler.rtb) {\n");
document.write("show_ad(window.adjuggler.rtb);\n");
document.write("} else {\n");
document.write("if (!window.adjuggler) {\n");
document.write("window.adjuggler = {\n");
document.write("waiting_ads : []\n");
document.write("};\n");
document.write("}\n");
document.write("window.adjuggler.waiting_ads.push(show_ad);\n");
document.write("}\n");
document.write("})();\n");
document.write("<"+"/script>");
